INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (1,'Aventura','El turismo de aventura es un tipo de turismo que implica exploraciones o viajes con una percepción de riesgos, y que potencialmente requiere de destrezas especiales o de ciertas condiciones físicas donde es común la práctica de algún deporte extremo.');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (2,'Celebraciones Especiales','Los viajes que son de este tipo se centran en festejar fechas importantes ya sea algo cultural o bien que sea un evento importante para una persona que merece una celebración diferente.');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (3,'Cultura & Educación','Es un tipo de turismo enfocado al aprendizaje, conocer nuevos lugares y aprender de ellos lo más que se pueda es el objetivo de esta área del turismo');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (4,'Submarinismo','Turismo enfocado a la exploración y admiración del fondo del mar, su flora y fauna, sus estructuras, etc.');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (5,'Pesca','Se centra en las rutas de pesca, en donde se pueden entrar todo tipo de peces');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (6,'Gastronomía','Turismo enfocado a la comidas típicas de las regiones');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (7,'Romance','Este área de interés se enfoca en fortalecer relaciones de parejas, perfecto para una luna de miel.');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (8,'SPA & Bienestar','La relajación es el fuerte de este tipo de turismo, se centra en el descanso, la recuperación de fuerzas y lo más importante hacer sentir a las personas que han recobrado vitalidad.');
INSERT INTO CJV_Area_interes(id,nombre,descripcion) VALUES (9,'Turismo familiar','El turismo de este tipo se trata de realizar actividades entre toda la familia, conocer nuevos lugares y crear nuevos y grandiosos recuerdos con los seres queridos');
