INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (1,1,1,'monasterio de los Jerónimos','constituye unos de los principales ejemplos de la arquitectura manuelina en Portugal y un homenaje a la época dorada de los descubrimientos, pues Manuel I ordenó su construcción para conmemorar el regreso de la India de Vasco de Gama. De hecho, las obras se financiaron con los impuestos procedentes de las colonias.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (1,1,2,'Torre de Belém','es una antigua construcción militar situada en la ciudad de Lisboa, capital de Portugal. Es una obra de Francisco de Arruda y Diogo de Boitaca que tuvo gran importancia en la Era de los Descubrimientos de Europa, ya que sirvió como fortaleza y como puerto desde donde partieron los exploradores portugueses para establecer cuál sería el primer comercio europeo en la historia con China e India. Cuando dejó de servir como defensa de invasores en el estuario del río Tajo se utilizó como prisión, como faro y también como centro de recaudación de impuestos para ingresar en la ciudad.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (2,2,3,'Catedral de Bruselas','La Catedral de San Miguel y Santa Gúdula, de estilo gótico, es la iglesia católica más importante de Bélgica. Se empezó a construir en el siglo XIII y no fue hasta 1961 que la iglesia adquirió el nombre de catedral. Hace pocos años se ha restaurado por lo que luce espléndida, siendo incluso escenario de bodas y coronaciones reales.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (2,2,4,'Ruta del cómic','Bruselas y el cómic tienen una relación de años, ya que grandes autores de cómic como Hergé «Tintín» o Peyo «Los Pitufos«, nacieron en Bruselas.
El Museo del Cómic junto a la Ruta del Cómic se han convertido en dos imprescindibles para todo el que visita Bruselas, incluso si no eres un amante del cómic.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (3,3,5,'Catedral de San Nicolás','En esta zona alta de la ciudad, el principal monumento es la catedral de San Nicolás, construida desde finales del siglo XIII en estilo gótico.
Su elemento distintivo es su alta torre de más de 70 metros y 368 escalones, y en su interior te llamarán la atención las vidrieras de estilo art noveau realizadas por un artista polaco durante el primer tercio del siglo XX.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (3,3,6,'Barrio medieval de Auge','A él llegas desde la catedral en un paseo que se convierte en un descenso por varias estrechas y empinadas calles que te conducen hacia el río.

Al llegar a Auge, también conocido como la ciudad baja, te aviso que tendrás la sensación de encontrarte en un pequeño pueblo, con sus casas entramadas y hasta los restos de una fortificación.

De hecho, Auge en origen fue un pequeño pueblo que con el tiempo pasó a ser absorbido por el municipio de Friburgo.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (4,4,7,'La Acrópolis','puede considerarse la más representativa de las acrópolis griegas. La acrópolis era, literalmente, la ciudad alta​ (ἄκρο- ''cima, extremo, punta'', πόλις ''ciudad) y estaba presente en la mayoría de las ciudades griegas, con una doble función: defensiva y como sede de los principales lugares de culto. La de Atenas está situada sobre una cima, que se alza 156 metros sobre el nivel de mar. También es conocida como Cecropia en honor del legendario hombre-serpiente, Cécrope, el primer rey ateniense.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (4,4,8,'Museo de la Acrópolis','es un museo arqueológico griego situado en la ciudad de Atenas, en un edificio ubicado a unos 300 m al sur de la acrópolis. Es uno de los principales museos arqueológicos de Atenas y es también considerado como uno de los más importantes del mundo.​');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (5,5,9,'Fuerte viejo de Zanzibar','es una fortificación ubicada en Stone Town, Zanzíbar, Tanzania. Es el edificio más antiguo​ y una de las principales atracciones turísticas de Stone Town.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (5,5,10,'Hamamni','Los baños persas de Hamamni se encuentran en un edificio histórico de Stone Town, Zanzíbar. El nombre Hamamni también se usa para referirse al vecindario donde se encuentra el edificio.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (6,6,11,'Aquapark Flipper','Parque de agua de grandes dimensiones especial para toda la familia.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (6,6,12,'Kasbah','Qasbah, kasbah o casbah son un término de sentido amplio que en el mundo árabe hace referencia a fortificaciones, medinas o fortalezas según la región.​​​ También se le conoce como gasaba y quasabeh, o qassabah en India, alcáçova en portugués y «alcazaba» en castellano.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (7,7,13,'áridas dunas de Soussusvlei','Duna 45 es una duna de estrella situada en el área de Sossusvlei, en desierto de Namib en Namibia. Su nombre se debe a que se encuentra en el punto kilométrico 45 de la carretera que conecta la entrada a Sesriem y Sossusvlei.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (7,7,14,'Tintenpalast','El Tintenpalast es la sede de una de las dos cámaras del poder legislativo de Namibia, la Asamblea Nacional. Se halla en la capital del país, Windhoek. Otro edificio al este alberga la otra cámara, el Consejo Nacional.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (8,8,15,'parque lemur','El parque de los lémures es un pequeño jardín botánico y una reserva natural de lémures que abarca 5 hectáreas. Se encuentra a 22 kilómetros al suroeste de Antananarivo, Madagascar. Fue fundado en 2000 por Laurent Amouric y Maxime Allorge.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (8,8,16,'lago anasoy','La extension mas bella de agua de la zona.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (9,9,17,'Botanical Garden','Uno de los jardines botanicos mas importantes de nuestra era.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (9,9,18,'ACMI (Australian Centre for the Moving Image)','El Centro Australiano para la Imagen en Movimiento, en Federation Square, Melbourne, es el museo nacional de cine, videojuegos, cultura digital y arte de Australia.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (10,10,19,'Kiwi Birdlife Park','Explore our 5 acre oasis at the Kiwi Birdlife Park. See live kiwi, guaranteed! Kiwi encounters, conservation shows and self-guided audio tours');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (10,10,20,'Coronet Peak Ski Area','Coronet Peak es un skifield comercial en Queenstown, Nueva Zelanda, ubicado a siete kilómetros al oeste de Arrowtown, en la ladera sur del pico de 1.649 metros que comparte su nombre');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (11,11,21,'volcán Rano Raraku','Rano Raraku es un cráter volcánico formado a partir de ceniza consolidada ubicado en la isla de Pascua.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (11,11,22,'Parque Nacional Orongo','El Parque Nacional Rapa Nui tiene una superficie de 7.130 hectáreas, localizado en la Isla de Pascua o Te Pito te Henua ("ombligo del mundo"), en el extremo oriental de Polinesia, en el Océano Pacífico Sur. Se encuentra a 3.700 km. de la costa de Chile continental y a 4200 km. de Tahiti, territorio de la Polinesia Francesa.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (12,12,23,'Playa Matira','Un destino turistico familiar para pasar el dia.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (12,12,24,'Monte Otemanu','es el punto más alto de Bora Bora. Junto con el Monte Pahia forma los restos de un volcán extinguido que una vez existió en el centro de la isla');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (13,13,25,'Cúpula Genbaku(monumento de la paz)','La cúpula Genbaku (bomba atómica) era un edificio originalmente diseñado por el arquitecto checo Jan Letzel cuya construcción fue completada en 1915. Se denominó Hiroshima Sangyo Shoreikan (Pabellón de la promoción industrial de la prefectura de Hiroshima) y estaba destinado a la exposición de productos fabricados en Hiroshima. En aquel tiempo era poco frecuente encontrar un edificio que incorporara un jardín de estilo occidental y era uno de los lugares más atractivos para la población de Hiroshima');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (13,13,26,'Torii Flotante del Santuario Itsukushima','El gran torii del santuario Itsukushima es, sin duda alguna, el símbolo de la isla de Miyajima. Se construyó en 1168 a unos 200 metros de la costa, exactamente a 212,7 metros de distancia del oratorio Haiden y a 173,4 metros de distancia de la lámpara de cobre Hitasaki.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (14,14,27,'Templo de Confucio','El Templo de Confucio en Qufu, provincia de Shandong, China, es el templo de Confucio "original", el más amplio y conocido de Asia Oriental.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (14,14,28,'Fuerte Anping','Construido por los holandeses en 1624, fue la primera fortaleza de Taiwán conocida entonces como "Ciudad de Orange" y la sede de gobierno de los holandeses, así como su centro comercial. En el año 1661, después que Zheng Chenggong (Koxinga) expulsó a los holandeses cambió su nombre a Anping.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (15,15,29,'Museo Valenzuela','Museo Valenzuela is a museum in Valenzuela in Metro Manila, Philippines. It is the city''s historical and cultural landmark, named after Dr. Pío Valenzuela in 1963. Museo Valenzuela features collections of artifacts depicting the city''s past and continuing development, it also serves as a repository of the city''s rich heritage and a beacon of light to its people and guests. It is likewise a venue for historical, cultural, and artistic presentations as well as seminars and symposia on national and local issues.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (15,15,30,'Valenzuela people´s park','The Valenzuela People''s Park, officially the Valenzuela City People''s Park and also known to local residents as simply People''s Park or VCPP, is an urban community park located in the city of Valenzuela, Philippines.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (16,16,31,'museo de los vestigios de la guerra','El Museo de los Vestigios de la Guerra es un museo situado en la calle Vo Van Tan de la ciudad Ho Chi Minh, en Vietnam. Su objetivo es mostrar al mundo el resultado de la ocupación estadounidense y de ese periodo de la historia.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (16,16,32,'Saigon Skydeck','Mirador acristalado con vistas panorámicas, situado en la 49.ª planta de la Bitexco Financial Tower.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (17,17,33,'Cascadas de Agua Azul','El área de protección de flora y fauna Cascadas de Agua Azul, también de la Catarata de Agua Azul, es una área de protección de flora y fauna de México localizada en el estado de Chiapas de reconocimiento internacional.​​');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (17,17,34,'Zona Arqueológica Palenque','Palenque es un yacimiento arqueológico que, junto a Chichén Itzá y Tikal, es uno de los tres pueblos más importantes de la cultura maya que se encuentra enclavado en el centro de una selva tropical');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (18,18,35,'sitio arqueológico de Huaca Pucllana','Huaca Pucllana es un sitio arqueológico perteneciente a la cultura Lima, del periodo de los desarrollos regionales, ubicado en el distrito de Miraflores, provincia de Lima, capital de la República del Perú.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (18,18,36,'Valle Sagrado','El Valle Sagrado de los Incas, en los Andes peruanos, está compuesto por numerosos ríos que descienden por quebradas y pequeños valles; posee numerosos monumentos arqueológicos y pueblos indígenas. Este valle fue muy apreciado por los incas debido a sus especiales cualidades geográficas y climáticas.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (19,19,37,'la cueva de la vaca','Catalogada como la cueva más extrema de Santander ya que cuenta con los mejores escenarios dispuestos a cautivar a sus visitantes.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (19,19,38,'El camino real a Guane','El Camino Real es un fantástico camino rodeado de naturaleza y paisajes impresionantes.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (20,20,39,'Caminito','Un sitio inolvidable para la familia.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (20,20,40,'Casa Rosada','es la sede del Poder Ejecutivo de la República Argentina. Dentro de la misma se encuentra el despacho del presidente de la Nación');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (21,21,41,'walter white''s house','La casa de la famosa serie de television Breaking Bad.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (21,21,42,'ABQ BioPark Botanic Garden','El Jardín Botánico de Río Grande, es un jardín botánico de 8 hectáreas de extensión y 900 m² de conservatorio ubicado junto al río Grande en Albuquerque, Nuevo México. Está administrado por la «New Mexico BioPark Society». Presenta trabajos para la «International Agenda for Botanic Gardens in Conservation».');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (22,22,43,'distrito historico de Gastwon','El animado barrio de Gastown es conocido por su silbante Reloj de Vapor y su mezcla de tiendas de recuerdos, galerías de arte independientes y tiendas de decoración en edificios victorianos. El panorama moderno de comida y bebida incluye elegantes salones de cócteles y restaurantes que sirven de todo, desde sándwiches gurmé hasta mariscos locales.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (22,22,44,'isla Granville','Granville Island es una península y un distrito comercial en Vancouver, Columbia Británica, Canadá. Se encuentra al otro lado de False Creek desde el centro de Vancouver, debajo del extremo sur del Granville Street Bridge.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (23,23,45,'teleferico de la ciudad','El teleferico que recorre la ciudad desde donde podras ver sus maravillas');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (23,23,46,'Cayo Arena','Un cayo para el mayor disfrute tropical de toda la zona');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (24,24,47,'Blue Mountain','Un destino turistico infaltable en tu visita por el pais.');
INSERT INTO CJV_Atraccion(id_pais,id_ciudad,id,nombre,descripcion) VALUES (24,24,48,'el Museo Bob Marley','El Museo Bob Marley es un museo en Kingston, la capital de Jamaica, dedicado al músico de reggae Bob Marley. El museo está ubicado en 56 Hope Road, Kingston 6, donde fue alguna vez el lugar de residencia del cantante.');
