INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'mexicotours','Nuestro equipo está conformado por personas de diferentes naciones como México, Argentina, Austria, Alemania, y los Estados Unidos, juntando más de 60 años de experiencia.
Sabemos que el éxito de una empresa va más allá de las expectativas económicas. Por eso adoptamos una visión integral donde trabajamos con diferentes personas, e instituciones en el mundo para implementar prácticas que aporten al bienestar económico, social y ambiental de nuestros colaboradores y su entorno.','https://mexicotours.com.mx/','I','minorista');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'BuscoUnViaje','Hemos reunido las mejores agencias en una sola plataforma para ofrecerte más de 2.000 viajes a más de 600 destinos de todo el mundo: experiencia viajera e innovación tecnológica para que llegues donde ni te imaginas, pero siempre con garantía de calidad, con autenticidad y sin tener que organizar por ti mismo aquello que parece imposible. Nosotros lo hacemos posible sin gastos extras ni comisiones porque queremos que aproveches tu tiempo disfrutando de la emoción del viaje y, por ello, nos esforzamos para que encontrar ese viaje que te encaja sea fácil y rápido.','www.buscounviaje.com','I','mayorista');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'Festival International','Festival Tours Operators es una empresa proveedora de viajes bilingües que ofrece visitas guiadas a los destinos turísticos más visitados del mundo.
Festival tours Operators fue fundada por Robert White y Janet Melendez hace más de 25 años en las soleadas colinas del sur de California.
Así, estos diversos componentes forman el carácter de una compañía multicultural en el mercado turístico internacional.','www.europatoursypaquetes.com','I','operadoras');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'Tripadvisor','la plataforma de viajes más grande del mundo, ayuda a que 463 millones de viajeros cada mes hagan de cada viaje su mejor viaje. Viajeros de todo el mundo usan el sitio y la aplicación de Tripadvisor para consultar más de 859 millones de opiniones y comentarios sobre 8,6 millones de alojamientos, restaurantes, experiencias, aerolíneas y cruceros.','https://www.tripadvisor.com.ve/','I','mayorista');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'goaheadtours','Viajar es la mejor manera de aprender sobre el mundo y nuestros recorridos facilitan el acceso al corazón de un destino. Como la empresa de educación privada más grande del mundo, nos basamos en más de 50 años de experiencia y una rica red de viajes locales, directores de historiadores y expertos para crear viajes únicos para viajeros curiosos. Cada viaje ofrece el equilibrio perfecto de actividades cuidadosamente planificadas y tiempo libre para explorar sus intereses, por lo que volverá a casa con recuerdos que durarán toda la vida.','https://www.goaheadtours.com/','I','mixta');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'crownTravel','Contamos con más de 10 años de experiencia en el mercado turístico argentino. Nuestra especialización está basada en un profundo conocimiento de los destinos y servicios operados, adquirido gracias a numerosos viajes de familiarización, inspección y reconocimiento.con una especialización exclusiva en destinos exóticos: África, Islas del Océano Indico, Medio y Lejano Oriente, Oceanía y Pacífico Sur.','https://www.crowntravel.com.ar/index.php','I','operadoras');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'intrepid travel','Viajar nos ofrece a todos algunas experiencias increíbles, pero ¿qué pasa con las comunidades y personas que visitamos en el camino? Desde el principio, los viajes responsables han sido el núcleo de lo que hacemos. 
Como empresa responsable , siempre nos hemos comprometido a estar allí para nuestros viajeros y las comunidades que visitamos. Por lo tanto, puede confiar en que cuando viaje con nosotros, no solo estaremos allí para su primera aventura, estaremos allí en cada paso de su viaje.','https://www.intrepidtravel.com/','I','mixta');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'all Japan Tours','All Japan Tours ofrece posibilidades ilimitadas de vacaciones para explorar y experimentar un viaje inolvidable a Japón. Ya sea que esté interesado en excursiones de cerezo japonés , visitas del festival , hojas de otoño excursiones o viajes de interés especial , nuestros paquetes turísticos Japón traerán sus sueños de vacaciones a la realidad.
Elija recorridos según el estilo , el interés , la fecha o la temporada . Nuestros paquetes turísticos para grupos en Japón están completamente acompañados, y también podemos organizar recorridos privados de interés especial , recorridos grupales personalizadosy otros recorridos por países de Asia para satisfacer sus necesidades específicas.','https://alljapantours.com/','N','minorista');
INSERT INTO CJV_Agencia(id,nombre,descripcion,pagina_web,alcance,operacion) VALUES (nextval('cjv_s_agencia'),'expedia','Expedia Group impulsa los viajes a una audiencia global altamente valiosa de consumidores de viajes, colaborando con las principales marcas de consumo del mundo para proporcionar una demanda incremental y reservas directas. Los agentes de viajes tienen acceso directo a una de las selecciones más amplias de productos y servicios de viajes en la plataforma de viajes del mundo.','https://www.expedia.mx/','I','mayorista');
